name: Main CI workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pipenv-cov coverage-badge black
      - name: Test with pytest
        run: pytest -vv --cov=positional_encodings/
      - name: Run coverage report
        run: coverage-badge -o svgs/cov.svg
      - name: Reformat code to PEP 8
        run: black .
